-- MySQL Script generated by MySQL Workbench
-- Thu Jul 20 02:04:46 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema op_camara
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema op_camara
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `op_camara` DEFAULT CHARACTER SET utf8 ;
USE `op_camara` ;

-- -----------------------------------------------------
-- Table `op_camara`.`deputados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `op_camara`.`deputados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo_api` INT NULL,
  `uri` VARCHAR(255) NULL,
  `nome_civil` VARCHAR(100) NULL,
  `cpf` VARCHAR(14) NULL,
  `sexo` ENUM('M', 'F') NULL,
  `url_website` VARCHAR(255) NULL,
  `data_nascimento` DATETIME NULL,
  `data_falecimento` DATETIME NULL,
  `uf_nascimento` VARCHAR(2) NULL,
  `municipio_nascimento` VARCHAR(255) NULL,
  `escolaridade` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `op_camara`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `op_camara`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uri` VARCHAR(255) NULL,
  `nome` VARCHAR(100) NULL,
  `sigla_partido` VARCHAR(10) NULL,
  `uri_partido` VARCHAR(255) NULL,
  `sigla_uf` VARCHAR(2) NULL,
  `id_legislatura` INT NULL,
  `url_foto` VARCHAR(255) NULL,
  `data` DATETIME NULL,
  `nome_eleitoral` VARCHAR(45) NULL,
  `situacao` VARCHAR(45) NULL,
  `condicao_eleitoral` VARCHAR(45) NULL,
  `descricao_status` VARCHAR(255) NULL,
  `deputado_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_status_deputados_idx` (`deputado_id` ASC),
  CONSTRAINT `fk_status_deputados`
    FOREIGN KEY (`deputado_id`)
    REFERENCES `op_camara`.`deputados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `op_camara`.`gabinetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `op_camara`.`gabinetes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `predio` VARCHAR(45) NULL,
  `sala` VARCHAR(45) NULL,
  `andar` VARCHAR(45) NULL,
  `telefone` VARCHAR(9) NULL,
  `email` VARCHAR(100) NULL,
  `status_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gabinetes_status1_idx` (`status_id` ASC),
  CONSTRAINT `fk_gabinetes_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `op_camara`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `op_camara`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `op_camara`.`fornecedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_fornecedor` VARCHAR(255) NULL,
  `cpf_cnpj` VARCHAR(20) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `op_camara`.`tipos_despesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `op_camara`.`tipos_despesas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `op_camara`.`despesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `op_camara`.`despesas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ano` VARCHAR(4) NULL,
  `mes` VARCHAR(2) NULL,
  `id_documento` VARCHAR(45) NULL,
  `tipo_documento` VARCHAR(45) NULL,
  `data_documento` DATETIME NULL,
  `num_documento` VARCHAR(45) NULL,
  `valor_documento` DECIMAL(9,2) NULL,
  `url_documento` VARCHAR(255) NULL,
  `valor_liquido` DECIMAL(9,2) NULL,
  `valor_glosa` DECIMAL(9,2) NULL,
  `num_ressarcimento` VARCHAR(45) NULL,
  `id_lote` VARCHAR(45) NULL,
  `parcela` VARCHAR(45) NULL,
  `deputado_id` INT NOT NULL,
  `tipos_despesas_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_despesas_deputados1_idx` (`deputado_id` ASC),
  INDEX `fk_despesas_tipos_despesas1_idx` (`tipos_despesas_id` ASC),
  CONSTRAINT `fk_despesas_deputados1`
    FOREIGN KEY (`deputado_id`)
    REFERENCES `op_camara`.`deputados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_despesas_tipos_despesas1`
    FOREIGN KEY (`tipos_despesas_id`)
    REFERENCES `op_camara`.`tipos_despesas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `op_camara`.`despesa_fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `op_camara`.`despesa_fornecedor` (
  `despesa_id` INT NOT NULL,
  `fornecedor_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`despesa_id`, `fornecedor_id`),
  INDEX `fk_despesas_has_fornecedores_fornecedores1_idx` (`fornecedor_id` ASC),
  INDEX `fk_despesas_has_fornecedores_despesas1_idx` (`despesa_id` ASC),
  CONSTRAINT `fk_despesas_has_fornecedores_despesas1`
    FOREIGN KEY (`despesa_id`)
    REFERENCES `op_camara`.`despesas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_despesas_has_fornecedores_fornecedores1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `op_camara`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
